model:
  checkpoint_path: "./models/aura_flow_0.3.bnb_nf4.safetensors"
  pretrained_model_name_or_path: fal/AuraFlow-v0.3

  dtype: bfloat16

peft:
  type: lora
  rank: 4
  alpha: 1.0
  dropout: 0.0

dataset:
  folder: "data/sfw_0.1k/images"
  num_repeats: 2
  batch_size: 2

  bucket_base_size: 1024
  step: 128
  min_size: 384
  do_upscale: false

optimizer:
  name: "schedulefree.RAdamScheduleFree"
  args:
    lr: 0.005

scheduler:
  # name: "torch.optim.lr_scheduler.ConstantLR"
  # args: {}

trackers:
  []
  # - name: wandb
  #   args:
  #     project: "mnist-1"

saving:
  # strategy:
  #   per_epochs: 5
  #   per_steps: null
  #   save_last: true

  # callbacks:
  #   - type: "hf_hub" # or "safentensors" to don't push to hub
  #     name: "mnist"
  #     save_dir: "./output/mnist"
  #     hub_id: "p1atdev/test"
  #     dir_in_repo: "/mnist-2"

seed: 42
num_train_epochs: 10

trainer:
  debug_mode: "dataset"

torch_compile: true
fp32_matmul_precision: "high"
