model:
  checkpoint_path: "./models/aura_flow_0.3.bnb_nf4.safetensors"
  pretrained_model_name_or_path: fal/AuraFlow-v0.3

  dtype: bfloat16

  denoiser:
    use_flash_attn: false

peft:
  type: lora
  rank: 4
  alpha: 1.0
  dropout: 0.0

  dtype: bfloat16

  include_keys: [".attn.", ".mlp.", ".modC.", ".modC.", ".modX."]
  exclude_keys: ["text_encoder", "vae", "t_embedder", "final_linear"]

dataset:
  folder: "data/sfw_0.1k/images"
  num_repeats: 4
  batch_size: 1

  bucket_base_size: 1024
  step: 128
  min_size: 384
  do_upscale: false

optimizer:
  name: "schedulefree.RAdamScheduleFree"
  # name: "bitsandbytes.optim.AdamW8bit"
  args:
    lr: 0.001

scheduler:
  # name: "torch.optim.lr_scheduler.ConstantLR"
  # args: {}

trackers:
  []
  # - name: wandb
  #   args:
  #     project: "mnist-1"

saving:
  strategy:
    per_epochs: 1
    per_steps: null
    save_last: true

  callbacks:
    - type: "safentensors" # or "safentensors" to don't push to hub
      name: "test-lora"
      save_dir: "./output/lora"

seed: 42
num_train_epochs: 10

trainer:
  debug_mode: "1step"

  gradient_checkpointing: true

  torch_compile: true
  torch_compile_args:
    mode: max-autotune
    fullgraph: true
  fp32_matmul_precision: "medium"
